name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'
      - name: Build with Maven
        run: ./mvnw --show-version --no-transfer-progress --errors --batch-mode package
